name: 🐛 Bug Report
description: Report a bug or problem with the extension
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees:
  - D-Town

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! The more details you provide, the faster we can help.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect?
      placeholder: |
        When I press Cmd+Shift+L, it...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Open a .ts file
        2. Select a variable
        3. Press Cmd+Shift+L
        4. Error appears...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
    validations:
      required: true

  - type: dropdown
    id: language
    attributes:
      label: Programming Language
      description: In which file type does the bug occur?
      options:
        - JavaScript (.js)
        - TypeScript (.ts)
        - JSX (.jsx)
        - TSX (.tsx)
        - Other
    validations:
      required: true

  - type: input
    id: vscode-version
    attributes:
      label: VSCode Version
      description: Which VSCode version are you using? (Help → About)
      placeholder: "1.95.0"
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: Which version of the extension are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Messages
      description: |
        If available: Error messages from Developer Console
        (Help → Toggle Developer Tools → Console Tab)
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Screenshots, GIFs, other details?

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have checked if this issue already exists
          required: true
        - label: I am using the latest version of the extension
          required: true